services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MEIO_ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
    depends_on:
      - elasticsearch

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "4174:80"
